# Required parameters
n_side_sites   =         30 # whole lattice will be (n_side_sites x n_side_sites) sites
n_measurements =      50000 # total number of measurements
n_HMC_steps    =         15 # average number of steps for each time evolution
dt             =      0.007 # single computer-time step amplitude
n_indep_comps  =         33 # number of independent components.
                            # The theory simulated will be O(N), N = n_indep_comps + 1
max_perturbative_order = 12 # maximum perturbative order.
                            # The theory simulated will be up to order g^max_perturbative_order,
                            # neglecting results of order g^(max_perturbative_order+1) or greater

# Optional parameters
measure_every =  7 # number of measurements to skip between two saved measures. Default = 1
n_copies      = 10 # number of lattice copies to be simulated in parallel. Default = 1
energy_site_by_site_matlab = "file.mat" # name of the matlab file to save the energy site-by-site. Default = ""
